[build]
  command = "cd vue-app && npm install && npm run build"
  publish = "vue-app/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/ranking-api/*"
  to = "/.netlify/functions/ranking-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth-api/*"
  to = "/.netlify/functions/auth-api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/legacy-ranking-api/*"
  to = "https://benbenkshen.cn/data/:splat"
  status = 200
  force = true
