[[redirects]]
  from = "/ranking-api/*"
  to = "https://t2s.awzh.cn/api/ranking/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/legacy-ranking-api/*"
  to = "https://benbenkshen.cn/data/:splat"
  status = 200
  force = true
